Add chapter on Solver and fix minor style issues
subdgtl/Monoceros pull request #11
Opened 2021-01-27 18:54 UTC by yanchith

@janper Is this satisfactory or did you envision something else? Also please note the PR is draft, because there are still TODOs in there for you to renumber the table of contents and re-generate the HTML docs.

2021-01-27 19:07 UTC, janper commented
could you also please explain:
1. how the solver turns non canonical set of slots into canonical
2. what is observation and that it is random
3. how the change triggered by an observation propagates

2021-01-27 19:23 UTC, yanchith commented
Sure I can, but 2) and 3) are vanilla WFC. If we are not counting on the reader already knowing this, then we have way more to explain throughout the entire document. If that's the case, I'd start with a chapter 0 describing vanilla WFC. I think I still do have that text lying around.

2021-01-27 19:26 UTC, janper commented
i don't like leaving blank spots, so I'd go for explaining as much as we can with as simple words as possible so that even we architects can understand

2021-01-27 19:30 UTC, yanchith commented
Ok, I agree, but then I would really start with a chapter called "What is Wave Function Collapse" somewhere early on. perhaps as 1.3 or 1.4 and explain WFC to the best of our ability there.

Then in the solver chapter, I'd address point 1), because that is our extension.

2021-01-27 19:32 UTC, janper commented
sure. if you don't want to do it completely on your own, you can assign certain paragraphs to me

2021-01-27 19:33 UTC, yanchith commented
I have already written that text last summer, we just didn't use it. Going to repurpose that.

2021-01-27 19:35 UTC, janper commented
please also review of it it digestible for non programmers (check with Subdigital?). the new text is on the verge of it

2021-01-27 19:36 UTC, yanchith commented
The text was already reviewed by at least @kr1sta2 and you :) I'll ask her to go through it again and post it on our internal channels.

2021-01-27 20:11 UTC, yanchith commented
The last commit reuses some of my old text to explain vanilla WFC. I am still going to explain point 1) you mentioned above in the solver chapter.

2021-01-27 20:58 UTC, janper requested changes

2021-01-27 20:58 UTC, janper commented on README.md
> +Wave Function Collapse (WFC) is an procedural generation algorithm that
a procedural 

generative (?)

2021-01-27 20:58 UTC, janper commented on README.md
> +the surface level - WFC is runs completely deterministically.
-is

2021-01-27 20:58 UTC, janper commented on README.md
> +Slot contains a list of Modules (conceptually geometry in case of Monoceros)
not sure they are a geometry. the bond between a module and its geometry is rather loose. the module parts are defined by points inside them, not the geometry stored in the module. 
i've been struggling with explaining this concept also in other parts of the docu, so maybe you can help me out somehow?

2021-01-27 20:58 UTC, janper commented on README.md
> +solution is computed very much depends on the set of provided Rules. There are
make bold

2021-01-27 20:58 UTC, janper commented on README.md
> +## 1.7. Solver
I'd make this peer to 1.4. Wave Function Collapse. i know this can't come before the three paragraphs on the data types, but it would be great if this started where 1.4 left off and started with a statement, that Monoceros WFC Solver (which should also be the heading of this paragraph) is an extension of the vanilla WFC (which as a term should be mentioned in 1.4) that differs in the following aspects...

2021-01-27 20:58 UTC, janper commented on README.md
> +process happens in the Solver component, where the Slots are observed guided by
"observed guided" sounds strange

2021-01-27 20:58 UTC, janper commented on README.md
> +Over the course of multiple iterations (called observations), Wave Function
shouldn't this be a paragraph after 1.7.1 Canonical World State?

2021-01-27 20:58 UTC, janper commented on README.md
> +predefined number of attempts, each attempt using the already modified PRGN
PRGN?

2021-01-27 20:58 UTC, janper commented on README.md
> +desugaring and reconstruction on the C# side of the language boundary. In the
shoudln't we call the C# side something like "Grasshopper wrapper" or so?

2021-01-27 20:58 UTC, janper commented on README.md
> +component that this happened, so that it can in turn notify the user.
Not anymore. It wasn't useful for the user.

What is useful is what step solver will do and we can mention it already here - the canonization of the world removes invalid neighborhoods, leaving a world in a state, that indicates which module can possibly end up where. indeed we have not exposed this feature yet but we can mention we'll include it in the coming releases.

2021-01-28 08:00 UTC, yanchith commented on README.md
> +Slot contains a list of Modules (conceptually geometry in case of Monoceros)
Ok, I would reword it to mention that a Module could be anything and that it is the user of the algorithm that assigns semantics to it, and I'll also list some examples of what people might want to assign, geometry being one of them.

Can you assign anything other than geometry to Modules in Monoceros? Speaking in broader contexts, other things that are usually assigned there are: images, navigation/collision geometry, descriptions (e.g. this is a park vs this is a skyscraper). Thoughts?

2021-01-28 08:03 UTC, yanchith commented on README.md
> +the surface level - WFC is runs completely deterministically.
Not sure I follow, which "is" would you like to remove?

(Btw github now has "suggestions", so if you see a mechanical change, you can just produce a diff to correct it in the github UI. It will create a review comment the PR author can just apply directly from the github UI)

2021-01-28 08:05 UTC, janper commented on README.md
> +Slot contains a list of Modules (conceptually geometry in case of Monoceros)
not directly. i was even hesitating with the geometry because you can deconstruct a Slot to get the inscribed Module name and with that you can do anything, including placing the geometry from a source different than the Module. but then it seemed too advanced for a general user to do. that is the only reason why the geometry is still a property of a Module

2021-01-28 08:07 UTC, janper commented on README.md
> +the surface level - WFC is runs completely deterministically.
WFC is runs

2021-01-28 08:09 UTC, yanchith commented on README.md
> +predefined number of attempts, each attempt using the already modified PRGN
Good catch. I meant PRNG. Or should I spell that out?

2021-01-28 08:12 UTC, janper commented on README.md
> +predefined number of attempts, each attempt using the already modified PRGN
i know it is obvious from the context but still, I'd go for the full wording

2021-01-28 08:13 UTC, yanchith commented on README.md
> +Over the course of multiple iterations (called observations), Wave Function
Depending on what we want to achieve with the chapter. I viewed the 1.7.1. Canonical World State more as a tangent, while the 1.7. more of a technical description of what is going on inside the Solver component, where the canonicalization is just one interesting thing that's happening. I can maybe change the paragraph about desugaring into its own chapter as well and extend it a bit.

2021-01-28 08:15 UTC, yanchith commented on README.md
> +desugaring and reconstruction on the C# side of the language boundary. In the
Whatever you prefer. I don't particularly like the word wrapper, so I tried to avoid it. I'd suggest "C# Grasshopper component" or "C# Grasshopper code"

2021-01-28 08:15 UTC, yanchith commented on README.md
> +component that this happened, so that it can in turn notify the user.
Ok, I'll reword it :)

2021-01-28 08:17 UTC, janper commented on README.md
> +Over the course of multiple iterations (called observations), Wave Function
i though it would be more chronological

2021-01-28 08:43 UTC, yanchith commented on README.md
> +predefined number of attempts, each attempt using the already modified PRGN
Used "random state" in the end :)

2021-01-28 08:47 UTC, yanchith commented on README.md
> +## 1.7. Solver
Yeah, they are related, but while 1.4. Wave Function Collapse is relevant to everyone, the 1.7. Monoceros WFC Solver is useful mostly for people wanting to understand the implementation, so it can come later in the docs. I'd do the following:

- Introduce the term "vanilla WFC" already in 1.4.
- Link back to 1.4. from 1.7. to restore the reader's context.

2021-01-28 09:41 UTC, yanchith commented on README.md
> +Slot contains a list of Modules (conceptually geometry in case of Monoceros)
Ah, okay. See what I did in the text. I mentioned that a Module could be anything, but that geometry is a common usecase

2021-01-28 09:42 UTC, yanchith commented on README.md
> +Over the course of multiple iterations (called observations), Wave Function
Please have a look if it works better after my last change.

2021-01-28 12:30 UTC, janper approved these changes

2021-01-28 13:17 UTC, yanchith commented
@janper If you are happy, I am happy. Merge when ready. You might also want to generate the HTML docs (not sure how you do that) so they are in sync.

2021-01-29 09:34 UTC, merged